name: Build Python Package Test

on:
  push:
    branches:
      - '**'
      - '!no-bulid-**'

  pull_request:
      types: [closed]
      branches:
        - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      
      - name: Build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: test-dists
          path: dist/